config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'gourmets/top' => 'gourmets#top'
get 'gourmets/Hokkaido' => 'gourmets#Hokkaido'
get 'gourmets/Tokyo' => 'gourmets#Tokyo'
get 'gourmets/Osaka' => 'gourmets#Osaka'
get 'gourmets/Fukuoka' => 'gourmets#Fukuoka'

get 'gourmets/Ginghiskhan' => 'gourmets#Ginghiskhan'
get 'gourmets/Kaisendon' => 'gourmets#Kaisendon'
get 'gourmets/Sappororamen' => 'gourmets#Sappororamen'
get 'gourmets/Hokkaidoelse' => 'gourmets#Hokkaidoelse'

get 'gourmets/Edomaezushi' => 'gourmets#Edomaezushi'
get 'gourmets/Monzyayaki' => 'gourmets#Monzyayaki'
get 'gourmets/Chankonabe' => 'gourmets#Chankonabe'
get 'gourmets/Tokyoelse' => 'gourmets#Tokyoelse'

get 'gourmets/Takoyaki' => 'gourmets#Takoyaki'
get 'gourmets/Okonomiyaki' => 'gourmets#Okonomiyaki'
get 'gourmets/Kushikatu' => 'gourmets#Kushikatu'
get 'gourmets/Osakaelse' => 'gourmets#Osakaelse'

get 'gourmets/Motunabe' => 'gourmets#Motunabe'
get 'gourmets/Hakataramen' => 'gourmets#Hakataramen'
get 'gourmets/Mizutaki' => 'gourmets#Mizutaki'
get 'gourmets/Fukuokaelse' => 'gourmets#Fukuokaelse'

get 'maps/index'
resources :maps, only: [:index]

resources :users do
  member do
  get :following, :followers
  end
end

resources :gourmets do
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]
end

resources :tests
resources :relationships, only: [:create, :destroy]
resources :messages, :only => [:create]
resources :rooms, :only => [:create, :show]

root  'gourmets#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gourmet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/gourmet.rb
class Gourmet < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :gourmet_tags, dependent: :destroy
    has_many :tags, through: :gourmet_tags
end

app/models/gourmet_tag.rb
class GourmetTag < ApplicationRecord
  belongs_to :gourmet
  belongs_to :tag
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gourmet
  belongs_to :user
  validates_uniqueness_of :gourmet_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true

    def change
        create_table :relationships do |t|
        t.integer :follower_id
        t.integer :following_id
    
        t.timestamps null: false
    end
    
    add_index :relationships, :follower_id
    add_index :relationships, :following_id
    add_index :relationships, [:follower_id, :following_id], unique: true
    end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gourmet_tags, dependent: :destroy
    has_many :gourmets, through: :gourmet_tags
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  
  has_many :gourmets, dependent: :destroy
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
  
  has_many :likes, dependent: :destroy
  has_many :liked_gourmets, through: :likes, source: :gourmet
  
  has_many :comments, dependent: :destroy
  
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def already_liked?(gourmet)
    self.likes.exists?(gourmet_id: gourmet.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @users=User.all
    end

    def show
        @user = User.find(params[:id]) 
        @currentUserEntry=Entry.where(user_id: current_user.id)
        @userEntry=Entry.where(user_id: @user.id)
            if @user.id == current_user.id
                @msg ="他のユーザーとDMしてみよう!"
            else
                @currentUserEntry.each do |cu|
                    @userEntry.each do |u|
                        if cu.room_id == u.room_id then
                        @isRoom = true
                        @roomId = cu.room_id
                        end
                    end
                end    
        
                if @isRoom != true
                    @room = Room.new
                    @entry = Entry.new
                end
            end
    end

    def following
        @user  = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end

    def followers
        @user  = User.find(params[:id])
        @users = @user.followers
        render 'show_follower'
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gourmets_helper.rb
module GourmetsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
        # calPercent = number/10.to_f * 100
        #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
        percent = calPercent.round
        #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
        return percent.to_s
        else
        return 0
        end
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
        # calPercent = number/10.to_f * 100
        #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
        percent = calPercent.round
        #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
        return percent.to_s
        else
        return 0
        end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :following_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
        <%= render 'unfollow' %>
        <% else %>
        <%= render 'follow' %>
        <% end %>
    </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
        <%= @user.followings.count %>
    </strong>
    following
    </a>
    <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
    <%= @user.followers.count %>
    </strong>
    followers
    </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/index.html.erb
<h1>DMサンプル</h1>
<h2>User一覧ページ</h2>

<% if user_signed_in? %>
    <h2><%= current_user.email %>でログインしています</h2> 
    <%= link_to "SignOut", destroy_user_session_path, :method => :delete, class:"signOutButton" %>
    
    <% number = 1%>
    <div class="flex">
        <% @users.each do |u| %>
        <div class="user-in">
            <p>プロフィール No.<%= number %></p>
            <p><%= u.email %>さん</p>
            <p><%= link_to 'ユーザーページへ', user_path(u.id) %></p>
        </div>  
        <% number += 1 %>
        <% end %>
    </div>

<% else %>
    <%= link_to "SignUp", new_user_registration_path %>
    <br>
    <%= link_to "SignIn", new_user_session_path %>
<% end %>


<style>
.signOutButton{
    text-decoration:none;
    display:inline-block;
    border:3px solid royalblue;
    background-color:aliceblue;
    padding:5px;
}
.flex{
    display:flex;
    flex-wrap:wrap;    
}
.user-in{
    display:block;
    width:300px;
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
    flex-shrink: 0;
}
</style>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="mypage2">

<div class="mypage">

<div class="photo-mypage">
  <div class="phototitle-mypage">
    My Page
  </div>
</div>

<div class="profile">
Profile
</div>

<div class="mypage-profile">

  <div class="mypage-profile-left">
    <div class="name">
      <div class="user_img">
        <%= image_tag @user.image_url, style: "border-radius: 50%; width: 100px; height: 100px; object-fit:cover;", size: "250x200" if @user.image?  %>
      </div>

      <div class="name1">
        <p>Name : <%= @user.name %></p>  
      </div>
    </div>

    <p>プロフィール : <%= @user.profile %></p>
    <br>

    <%= render 'follow_form' %>
    <%= render 'stats' %>

      <div class="edit">
        <% if current_user.id == @user.id %>
          <%= link_to "Edit", edit_user_registration_path %>
        <% end %>
      </div>
    </div>
  </div>

</div>


<div class="tabs">
  <input id="all" type="radio" name="tab_item" checked>
  <label class="tab_item" for="all">過去の投稿</label>
  <input id="programming" type="radio" name="tab_item">
  <label class="tab_item" for="programming">いいねした投稿</label>
  
  <div class="tab_content" id="all_content">
    <div class="tab_content_description">
      <p class="c-txtsp">
        <div class="box100">
          <% @user.gourmets.each do |t| %>
              <%= link_to gourmet_path(t.id) do %>
              <%= image_tag t.image_url,  class:"slide-image101" if t.image? %>
              <% end %>
          <% end %>
        </div>
      </p>
    </div>
  </div>

  <div class="tab_content" id="programming_content">
    <div class="tab_content_description">
      <p class="c-txtsp">
        <div class="box200">
          <% @user.liked_gourmets.each do |t| %>
            <%= link_to gourmet_path(t.id) do %>
              <%= image_tag t.image_url,  class:"slide-image201" if t.image? %>
            <% end %>
          <% end %>
        </div>
      </p>
    </div>
  </div>
</div>

</div>
</div>


<!--
  <div class="mypage-profile-right">

    <h2>ユーザー詳細ページ</h2>

    <div class="user-in">
      <h2><%= @user.email %></h2>
      <% if @user.id == current_user.id %>
        <%= @msg %>
      <% else %>
        <% if @isRoom == true %>
            <p><%= link_to 'DMへ', room_path(@roomId) %></p>
        <% else %>
          <%= form_for @room do |f| %>
            <%= fields_for @entry do |e|%>
              <% e.hidden_field :user_id, value: @user.id %>
        <% end %>
          <%= f.submit "DMを開始する"%>
          <% end %>
        <% end %>
      <% end %>
    </div>  

    <%= link_to "ユーザー一覧に戻る", users_path %>

    <style>
    .user-in{
    width:300px;
    padding:10px;
    margin:10px;
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
    }
    </style>

    <h2>過去の投稿</h2>
    <div class="box1">
      <% @user.gourmets.each do |t| %>
      <div class="image1">
        <%= image_tag t.image_url, size: "250x200" if t.image? %>
      </div>
      <% end %>
    </div>

<div class="mypage-like1">
  <div class="title-mypage-like">
    <h2>いいねした投稿一覧</h2>
    <% @user.liked_gourmets.each do |t| %>
  </div>
    
  <div class="image2">
    <div class="user_img">
      <%= image_tag t.user.image_url, style: "border-radius: 50%; width: 100px; height: 100px; object-fit:cover;", size: "250x200" if t.user.image? %>
    </div>

    <div class="mypage-like-username">
      <%= link_to t.user.name, user_path(t.user.id) %>
    </div>  

    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <% end %>
  </div>
</div>
-->

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<tr>
    <td>  <%= user.name %> </td>
    <td><%= link_to '詳細', user_path(user) %></td>
</tr>
    
</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
    <td>  <%= user.name %> </td>
    <td><%= link_to '詳細', user_path(user) %></td>
</tr>
    
</table>
<% end %>