config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'gourmets/top' => 'gourmets#top'
get 'gourmets/Hokkaido' => 'gourmets#Hokkaido'
get 'gourmets/Tokyo' => 'gourmets#Tokyo'
get 'gourmets/Osaka' => 'gourmets#Osaka'
get 'gourmets/Fukuoka' => 'gourmets#Fukuoka'

get 'gourmets/Ginghiskhan' => 'gourmets#Ginghiskhan'
get 'gourmets/Kaisendon' => 'gourmets#Kaisendon'
get 'gourmets/Sappororamen' => 'gourmets#Sappororamen'
get 'gourmets/Hokkaidoelse' => 'gourmets#Hokkaidoelse'

get 'gourmets/Edomaezushi' => 'gourmets#Edomaezushi'
get 'gourmets/Monzyayaki' => 'gourmets#Monzyayaki'
get 'gourmets/Chankonabe' => 'gourmets#Chankonabe'
get 'gourmets/Tokyoelse' => 'gourmets#Tokyoelse'

get 'gourmets/Takoyaki' => 'gourmets#Takoyaki'
get 'gourmets/Okonomiyaki' => 'gourmets#Okonomiyaki'
get 'gourmets/Kushikatu' => 'gourmets#Kushikatu'
get 'gourmets/Osakaelse' => 'gourmets#Osakaelse'

get 'gourmets/Motunabe' => 'gourmets#Motunabe'
get 'gourmets/Hakataramen' => 'gourmets#Hakataramen'
get 'gourmets/Mizutaki' => 'gourmets#Mizutaki'
get 'gourmets/Fukuokaelse' => 'gourmets#Fukuokaelse'

get 'maps/index'
resources :maps, only: [:index]

resources :users do
  member do
  get :following, :followers
  end
end

resources :gourmets do
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]
end

resources :tests
resources :relationships, only: [:create, :destroy]
resources :messages, :only => [:create]
resources :rooms, :only => [:create, :show]

root  'gourmets#top'
end

app/models/gourmet.rb
class Gourmet < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :gourmet_tags, dependent: :destroy
    has_many :tags, through: :gourmet_tags
end

app/controllers/gourmets_controller.rb
class GourmetsController < ApplicationController
  before_action :authenticate_user!, only: [:top, :index, :new, :create]
  
  def top
  end

  def index
    @gourmets = Gourmet.all
      if params[:search] == nil
      @gourmets = params[:tag_id].present? ? Tag.find(params[:tag_id]).gourmets : Gourmet.all
      elsif params[:search] == ''
      @gourmets = params[:tag_id].present? ? Tag.find(params[:tag_id]).gourmets : Gourmet.all
      else
      @gourmets = Gourmet.where("storename LIKE ? OR menu LIKE ? OR place LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
      end
    @gourmets = @gourmets.page(params[:page]).per(3)

  end
  

  def new
    @gourmet = Gourmet.new
  end
    
  def create
    gourmet = Gourmet.new(gourmet_params)
    gourmet.user_id = current_user.id
    if gourmet.save!
        redirect_to :action => "index"
    else
          redirect_to :action => "new"
    end
  end

  def show
    @gourmet = Gourmet.find_by(id: params[:id])
    @comments = @gourmet.comments
    @comment = Comment.new
  end

  def edit
    @gourmet = Gourmet.find(params[:id])
  end

  def update
    gourmet = Gourmet.find(params[:id])
      if gourmet.update(gourmet_params)
        redirect_to :action => "show", :id => gourmet.id
      else
      redirect_to :action => "new"
      end
  end
    
  def destroy
    gourmet = Gourmet.find(params[:id])
    gourmet.destroy
    redirect_to action: :index
  end

  def Hokkaido
    @Hokkaido = Gourmet.where(prefecture:"北海道")
  end
      
  def Tokyo
    @Tokyo = Gourmet.where(prefecture:"東京")
  end
      
  def Osaka
    @Osaka = Gourmet.where(prefecture:"大阪")
  end

  def Fukuoka
    @Fukuoka = Gourmet.where(prefecture:"福岡")
  end

  def Ginghiskhan
    @Ginghiskhan = Gourmet.where(food:"ジンギスカン")
  end

  def Kaisendon
    @Kaisendon = Gourmet.where(food:"海鮮丼")
  end

  def Sappororamen
    @Sappororamen = Gourmet.where(food:"札幌ラーメン")
  end

  def Hokkaidoelse
    @Hokkaidoelse = Gourmet.where(food:"その他")
  end

  def Edomaezushi
    @Edomaezushi = Gourmet.where(food:"江戸前寿司")
  end

  def Monzyayaki
    @Monzyayaki = Gourmet.where(food:"もんじゃ焼き")
  end

  def Chankonabe
    @Chankonabe = Gourmet.where(food:"ちゃんこ鍋")
  end

  def Tokyoelse
    @Tokyoelse = Gourmet.where(food:"その他")
  end

  def Takoyaki
    @Takoyaki = Gourmet.where(food:"たこ焼き")
  end

  def Okonomiyaki
    @Okonomiyaki = Gourmet.where(food:"お好み焼き")
  end

  def Kushikatu
    @Kushikatu = Gourmet.where(food:"串カツ")
  end

  def Osakaelse
    @Osakaelse = Gourmet.where(food:"その他")
  end

  def Motunabe
    @Motunabe = Gourmet.where(food:"もつ鍋")
    @Motunabe = @Motunabe.page(params[:page]).per(6)
  end

  def Hakataramen
    @Hakataramen = Gourmet.where(food:"博多ラーメン")
  end

  def Mizutaki
    @Mizutaki = Gourmet.where(food:"水炊き")
  end

  def Fukuokaelse
    @Fukuokaelse = Gourmet.where(food:"その他")
  end

  private
    def gourmet_params
      params.require(:gourmet).permit(:prefecture, :food, :shop_name, :about_shop, :price, :address, :image, :tag_ids, :overall, :level, :lat, :lng)
    end
end

app/helpers/gourmets_helper.rb
module GourmetsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
        # calPercent = number/10.to_f * 100
        #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
        percent = calPercent.round
        #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
        return percent.to_s
        else
        return 0
        end
    end
end

app/views/gourmets/Ginghiskhan.html.erb
<h1>ジンギスカン</h1>
    <% @Ginghiskhan.each do |t| %>
    <% if t.food == "ジンギスカン" %>  
    <p>内容:</p>
    <% end %>
<% end %>

app/views/gourmets/Motunabe.html.erb
<div class="photo-Motunabe">
  <div class="phototitle-Motunabe">
    もつ鍋
  </div>
</div>

<!--
<div class="img-box">
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
</div>
-->

<!--
<div class="slideBox">
  <img class="item1" src="assets/images/Motunabe11.jpg" alt="">
  <img class="item1" src="assets/images/Motunabe22.jpg" alt="">
  <img class="item1" src="assets/images/Motunabe33.jpg" alt="">
</div>
-->

<div class="slideBox">
<p class="title">もつ鍋</p>
  <%= image_tag "Motunabe11.jpg", class:"item1" %>
  <%= image_tag "Motunabe22.jpg", class:"item1" %>
  <%= image_tag "Motunabe33.jpg", class:"item1" %>
</div>


<div class="Motunabe-pagenation">
<%= page_entries_info @Motunabe %>
<%= paginate @Motunabe %>
<div>

<div class="Motunabebox">

<% @Motunabe.each do |t| %>
<% if t.food == "もつ鍋" %>
  <div class="Motunabe-gourmets-container">
    <div class="gourmet">
      <div class="user_img">
        <%= image_tag t.user.image_url, style: "border-radius: 50%; width: 100px; height: 100px; object-fit:cover;", size: "250x200" if t.user.image? %>
      </div>

      <div class="detail">
        <% t.tags.each do |tag| %>
          <%= tag.name %>
        <% end %> 

        店名：<%= t.shop_name %>
        <br>
        価格：<%= t.price %> 
        <br>
        住所：<%= t.addres %>  
    
        <div>
        総合評価：
          <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
          </span> 
        </div>
      </div>  
    </div>

    <div class="photo-Motunabe">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
    </div>

    <div class="detail2">
    <%= link_to "詳細", gourmet_path(t.id) %>

    <br>

    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.created_at %>

    <br>

    <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
        <%= link_to gourmet_like_path(id: t.id, gourmet_id: t.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
      <% else %>
        <%= link_to gourmet_likes_path(id: t.id, gourmet_id: t.id), method: :gourmet do %>
        <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="fas fa-heart"></i><%= t.likes.count %>
    <% end %>

    <br>

    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集", edit_gourmet_path(t.id) %>
      <%= link_to "削除", gourmet_path(t.id), method: :delete %>
    <% end %> 

    </div>  
  </div>
<% end %>
<% end %>

</div>

app/views/gourmets/index.html.erb
<div class="photo-index">
  <div class="phototitle-index">
    Search
  </div>
</div>

<!--
<%= form_tag gourmets_path, method: :get, class: 'boards__searchForm' do %>
  <%= select_tag :tag_id,
    options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
    {prompt: '都道府県を選択する',onchange: 'submit(this.form);'
    }   
  %>
<% end %>
-->

<div class="area1">
  <div class="Hokkaido">
    <a href="/gourmets/Hokkaido"><h3>北海道</h3></a>
  </div>

  <div class="Tokyo">
    <a href="/gourmets/Tokyo"><h3>東京</h3></a>
  </div>
</div>

<div class="area2">
  <div class="Osaka">
    <a href="/gourmets/Osaka"><h3>大阪</h3></a>
  </div>

  <div class="Fukuoka">
    <a href="/gourmets/Fukuoka"><h3>福岡</h3></a>
  </div>
</div>





<!--
<section id="Hokkaido-block">
  <h2>北海道のご当地グルメ</h2>
  <div class="area"> 
    <h2>ジンギスカン</h2>
    <%= link_to "ジンギスカンのお店はこちら", gourmets_Ginghiskhan_path %>
    <br>
    <h2>海鮮丼</h2>
    <%= link_to "海鮮丼のお店はこちら", gourmets_Kaisendon_path %>
    <br>
    <h2>札幌ラーメン</h2>
    <%= link_to "札幌ラーメンのお店はこちら", gourmets_Sappororamen_path %>
    <br>
    <h2>その他</h2>
    <%= link_to "その他のお店はこちら", gourmets_Hokkaidoelse_path %>
    <br>
    <%= link_to "北海道のご当地グルメ一覧", gourmets_Hokkaido_path %>
  </div>
</section>

<section id="Tokyo-block">
  <h2>東京のご当地グルメ</h2>
  <div class="area"> 
    <h2>江戸前寿司</h2>
    <%= link_to "江戸前寿司のお店はこちら", gourmets_Edomaezushi_path %>
    <br>
    <h2>もんじゃ焼き</h2>
    <%= link_to "もんじゃ焼きのお店はこちら", gourmets_Monzyayaki_path %>
    <br>
    <h2>どじょう鍋</h2>
    <%= link_to "どじょう鍋のお店はこちら", gourmets_Chankonabe_path %>
    <br>
    <h2>その他</h2>
    <%= link_to "その他のお店はこちら", gourmets_Tokyoelse_path %>
    <br>
    <%= link_to "東京のご当地グルメ", gourmets_Tokyo_path %>
  </div>
</section>

<section id="Osaka-block">
  <h2>大阪のご当地グルメ</h2>
  <div class="area"> 
    <h2>たこ焼き</h2>
    <%= link_to "たこ焼きのお店はこちら", gourmets_Takoyaki_path %>
    <br>
    <h2>お好み焼き</h2>
    <%= link_to "お好み焼きのお店はこちら", gourmets_Okonomiyaki_path %>
    <br>
    <h2>串カツ</h2>
    <%= link_to "串カツのお店はこちら", gourmets_Kushikatu_path %>
    <br>
    <h2>その他</h2>
    <%= link_to "その他", gourmets_Osakaelse_path %>
    <br>
    <%= link_to "大阪のご当地グルメ", gourmets_Osaka_path %>
  </div>
</section>

<section id="Fukuoka-block">
  <h2>福岡のご当地グルメ</h2>
  <div class="area"> 
    <%= link_to "福岡のご当地グルメ", gourmets_Fukuoka_path %>
    <h2>もつ鍋</h2>
    <%= link_to "もつ鍋のお店はこちら", gourmets_Motunabe_path %>
    <br>
    <h2>博多ラーメン</h2>
    <%= link_to "博多ラーメンのお店はこちら", gourmets_Hakataramen_path %>
    <br>
    <h2>水炊き</h2>
    <%= link_to "水炊きのお店はこちら", gourmets_Mizutaki_path %>
    <br>
    <h2>その他</h2>
    <%= link_to "その他のお店はこちら", gourmets_Fukuokaelse_path %>
  </div>
</section>
-->

<!--
<%= page_entries_info @gourmets %>
<%= paginate @gourmets %>

<div class="index-gourmets-container">
  <% @gourmets.each do |t| %>
    <div class="gourmet">
      <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
        <% t.tags.each do |tag| %>
          <%= tag.name %>
        <% end %> 

        <br>
        都道府県：<%= t.prefecture %>
        <br>
        ご当地グルメ：<%= t.food %>
        <br>
        お店：<%= t.shop_name %>
        <br>
        価格：<%= t.price %> 円
        <br>
        詳細：<%= t.about_shop %>
        <br>
        住所：<%= t.addres %>  
      
    <div>
      <h2>総合評価：
      <span class="star-rating">
      <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
      <span class="star-rating-back">★★★★★</span>
      </span> 
      </h2>
    </div>
  
    <%= link_to "詳細", gourmet_path(t.id) %>

    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集", edit_gourmet_path(t.id) %>
      <%= link_to "削除", gourmet_path(t.id), method: :delete %>
    <% end %> 
  
    <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
        <%= link_to gourmet_like_path(id: t.id, gourmet_id: t.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
      <% else %>
        <%= link_to gourmet_likes_path(id: t.id, gourmet_id: t.id), method: :gourmet do %>
        <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="fas fa-heart"></i><%= t.likes.count %>
    <% end %>
    <br>
    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.created_at %>
  </div>
  <% end %>
</div>
-->

<!--
<div id='map'></div>
-->

<style>
#map
{
  height: 600px;
  width: 100%;
}
</style>



<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
          {
            stylers: [
            { "saturation": 0 },
            { "lightness": 0 }
            ]
          }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @gourmets.each do |gourmet|%>
        ( function() { 
          let markerLatLng = { lat: <%= gourmet.lat %>, lng: <%= gourmet.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= gourmet_url(gourmet.id) %>' target='_blank'></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

      })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5YiQlX3PMEI7d7V-aL41HctWXVVCe8oU&callback=initMap" async defer></script>

app/views/gourmets/show.html.erb
<% @gourmet.tags.each do |tag| %>
  <%= tag.name %>
<% end %>

<div class="detail-gourmet-container1">
  <div class="detail-gourmet-container2">
  <%= image_tag @gourmet.image_url, size: "250x200" if @gourmet.image? %>
    <p>ご当地グルメ：<%= @gourmet.food %></p>
    <p>店名：<%= @gourmet.shop_name %></p>
    <p>価格：<%= @gourmet.price %></p>
    <p>住所：<%= @gourmet.addres %></p>
    <p>詳細：<%= @gourmet.about_shop %></p>
  
  <div>
  <h2>総合評価：
  <span class="star-rating">
  <span class="star-rating-front" style="width: <%= getPercent(@gourmet.overall) %>%;">★★★★★</span>
  <span class="star-rating-back">★★★★★</span>
  </span> 
  </h2>
  </div>
  
  <p><%= @gourmet.created_at %></p>
  
</div>  

<br>

<div class="map-title">
  <h2>Map</h2>
</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @gourmet.lat %>, lng: <%= @gourmet.lng %>},
    zoom: 15,
  });

  marker = new google.maps.Marker({
    position:  {lat: <%= @gourmet.lat %>, lng: <%= @gourmet.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5YiQlX3PMEI7d7V-aL41HctWXVVCe8oU
&callback=initMap" async defer></script>
  
  <% if user_signed_in? %>
    <% if current_user.already_liked?(@gourmet) %>
      <%= link_to gourmet_like_path(@gourmet), method: :delete do %>
      <i class="fas fa-heart"></i><%= @gourmet.likes.count %>
    <% end %>
  <% else %>
    <%= link_to gourmet_likes_path(@gourmet), method: :post do %>
    <i class="fas fa-heart"></i><%= @gourmet.likes.count %>
    <% end %>
  <% end %>
  <% else %>
    <i class="fas fa-heart"></i><%= @gourmet.likes.count %>
  <% end %>

<h2>いいねしたユーザー</h2>
<% @gourmet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

  <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
      <br>
    <% end %>

    <% if user_signed_in? %>
      <%= form_with(model: [@gourmet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>

  </div>
    <%= link_to "編集", edit_gourmet_path(@gourmet.id) %>
  </div>

app/views/gourmets/top.html.erb
<%= link_to "ご当地グルメ一覧", gourmets_path %>  

<body>


<!--   First block Start   -->
<!--
<div class="first-block">
  <div class="top-title-container">
    <h1>-ご当地グルメ紹介サイト-</h1>
  </div>
</div>
-->
<!--   First block End   -->

<div class="d-demo">
<p class="top-title">EaTravel</p>
  <div class="d-demo__wrap">
    <div class="d-demo__list d-demo__list--left">
      <div class="d-demo__item"><%= image_tag "Ginghiskhan11.jpg", class:"slide-image" %></div>
      <div class="d-demo__item"><%= image_tag "Kaisendon1.jpg", class:"slide-image" %></div>
      <div class="d-demo__item"><%= image_tag "Edomaemonzya.jpg", class:"slide-image" %></div>
      <div class="d-demo__item"><%= image_tag "Edomaezushi1.jpg", class:"slide-image" %></div>
      <div class="d-demo__item"><%= image_tag "Monzyayaki1.jpg", class:"slide-image" %></div>
      <div class="d-demo__item"><%= image_tag "Takoyaki1.jpg", class:"slide-image" %></div>
    </div>
    <div class="d-demo__list d-demo__list--left">
    <div class="d-demo__item"><%= image_tag "Ginghiskhan11.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Kaisendon1.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Edomaemonzya.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Edomaezushi1.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Monzyayaki1.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Takoyaki1.jpg", class:"slide-image" %></div>
    </div>
    <div class="d-demo__list d-demo__list--left">
    <div class="d-demo__item"><%= image_tag "Ginghiskhan11.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Kaisendon1.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Edomaemonzya.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Edomaezushi1.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Monzyayaki1.jpg", class:"slide-image" %></div>
    <div class="d-demo__item"><%= image_tag "Takoyaki1.jpg", class:"slide-image" %></div>
    </div>
  </div>
</div>


<!--   Second block Start   -->
  <div class="second-block">
    <p class="title-about">
      -About-
    </p>
    <div class="about-container">
      <span class="font-small">
        
      </span>
    </div>
  </div>
<!--   Second block End   -->
  
<!--   Third block Start   -->
<div class="third-block">
  <p class="title-feature">
  -Feature-
  </p>
    <div class="feature-container">
      <p class="info-text">
        <b>Seacrh</b>
        <br>
        <%= link_to gourmets_path do %>
        <%= image_tag "search.avif", class:"feature-image" %>
        <% end %>
        <br>
          <span class="font-small">
          ~ご当地グルメが食べられるお店を探す~
          </span>
      </p>

      <p class="info-text">
        <b>Test</b>
        <br>
        <%= link_to new_test_path do %>
        <%= image_tag "test.jpg", class:"feature-image" %>
        <% end %>
        <br>
        <span class="font-small">
        ~おすすめのご当地グルメを診断する~
        </span>
      </p>

      <p class="info-text">
        <b>Post</b>
        <br>
        <%= link_to new_gourmet_path do %>
        <%= image_tag "post.jpg", class:"feature-image" %>
        <% end %>
        <br>
        <span class="font-small">
        ~おすすめのお店を共有する~
        </span>
      </p>

      <p class="info-text">
        <b>My page</b>
        <br>
        <%= link_to user_path(current_user.id) do %>
        <%= image_tag "mypage.jpg", class:"feature-image" %>
        <% end %>
        <br>
        <span class="font-small">
        ~お気に入りの保存~
        </span>
      </p>
    </div>
</div>
<!--   Third block End   -->
</body>